# USERS

### Register
POST https://localhost:8085/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "email": "test@mail.com",
    "password": "123"
}

### Login
POST https://localhost:8085/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "test2",
    "email": "",
    "password": "123"
}

### Logout
POST https://localhost:8085/api/auth/logout HTTP/1.1
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzA5OTc3MDgzfQ.Jz4yC7wfb84yzqrbhP-sNpoF4GcRM577TZu5Gw6HVSpUHIORfUd2SfdptojIh8xOoJOSCSWNR3slCtTZ02Vtxw"
}

### Get users
GET https://localhost:8085/api/users HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzA5OTc3MDgzfQ.Jz4yC7wfb84yzqrbhP-sNpoF4GcRM577TZu5Gw6HVSpUHIORfUd2SfdptojIh8xOoJOSCSWNR3slCtTZ02Vtxw

### Get user 


# POSTS

### Create a post
POST https://localhost:8085/api/posts HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzA5OTc3MDgzfQ.Jz4yC7wfb84yzqrbhP-sNpoF4GcRM577TZu5Gw6HVSpUHIORfUd2SfdptojIh8xOoJOSCSWNR3slCtTZ02Vtxw
Content-Type: application/json

{
    "user_id": 1,
    "related_to_post": null,
    "text": "Test text of the post"
}

### Get a post
GET https://localhost:8085/api/posts/1 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzA5OTc3MDgzfQ.Jz4yC7wfb84yzqrbhP-sNpoF4GcRM577TZu5Gw6HVSpUHIORfUd2SfdptojIh8xOoJOSCSWNR3slCtTZ02Vtxw

### Like a post
POST https://localhost:8085/api/posts/1/like HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzA5OTc3MDgzfQ.Jz4yC7wfb84yzqrbhP-sNpoF4GcRM577TZu5Gw6HVSpUHIORfUd2SfdptojIh8xOoJOSCSWNR3slCtTZ02Vtxw

### Edit a post
PATCH https://localhost:8085/api/posts/2 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzA5OTc3MDgzfQ.Jz4yC7wfb84yzqrbhP-sNpoF4GcRM577TZu5Gw6HVSpUHIORfUd2SfdptojIh8xOoJOSCSWNR3slCtTZ02Vtxw
Content-Type: application/json

{
    "text": "Updated text"
}

### Delete a post
DELETE https://localhost:8085/api/posts/3 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzA5OTc3MDgzfQ.Jz4yC7wfb84yzqrbhP-sNpoF4GcRM577TZu5Gw6HVSpUHIORfUd2SfdptojIh8xOoJOSCSWNR3slCtTZ02Vtxw
